SELECT 'youngest' AS type, NAME, BIRTHDATE
FROM WORKER
WHERE BIRTHDATE = (SELECT MIN(BIRTHDATE) FROM WORKER)

UNION

SELECT 'oldest' AS type, NAME, BIRTHDATE
FROM WORKER
WHERE BIRTHDATE = (SELECT MAX(BIRTHDATE) FROM WORKER);