DROP TABLE IF EXISTS PROJECT_WORKER;
DROP TABLE IF EXISTS WORKER;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS PROJECT;

CREATE TABLE IF NOT EXISTS WORKER
(
    ID       SERIAL                             NOT NULL,
    NAME      VARCHAR(1000)                                  NOT NULL,
    BIRTHDATE DATE DEFAULT '1900-01-01'                      NOT NULL,
    LEVEL VARCHAR(10) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY    INT  DEFAULT 100                               NOT NULL,
    CONSTRAINT worker_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CLIENT
(
    ID SERIAL NOT NULL,
    NAME VARCHAR(1000)      NOT NULL,
    CONSTRAINT client_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PROJECT
(
    ID SERIAL NOT NULL,
    CLIENT_ID   INT                NOT NULL,
    NAME        VARCHAR(1000)      NOT NULL,
    START_DATE  DATE               NOT NULL,
    FINISH_DATE DATE               NOT NULL,
    CONSTRAINT project_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PROJECT_WORKER
(
    PROJECT_ID INT NOT NULL,
    WORKER_ID  INT NOT NULL,
    CONSTRAINT project_worker_pk PRIMARY KEY (PROJECT_ID, WORKER_ID),
    CONSTRAINT project_fk FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID),
    CONSTRAINT worker_fk FOREIGN KEY (WORKER_ID) REFERENCES WORKER (ID)
);