SELECT
    p.NAME AS Name,
    COALESCE(SUM(w.SALARY) * EXTRACT(MONTH FROM AGE(p.FINISH_DATE, p.START_DATE)), 0) AS Price
FROM
    PROJECT p
LEFT JOIN
    PROJECT_WORKER pw ON p.ID = pw.PROJECT_ID
LEFT JOIN
    WORKER w ON pw.WORKER_ID = w.ID
GROUP BY
    p.ID, p.NAME
ORDER BY
    Price DESC;